sudo: required
services:
    - docker
    
before_intall:
    - docker build -t crazylavendar/docker-react -f Dockerfile.dev .

script:
    - docker run crazylavendar/docker-react npm run test -- --coverage