sudo: required
services:
    - docker
    
before_intall:
    - docker build -t crazylavendar/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true crazylavendar/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: docker
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-us-east-1-317992000363"
    bucket_path: "docker"
    on:
        branch: master
        access_key-id: "$AWS_ACCESS_KEY"
        secret_access_key:
            secure: "$AWS_SECRET_KEY"