sudo: required
services:
    - docker
    
before_intall:
    - docker build -t crazylavendar/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true crazylavendar/docker-react npm run test